// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZOlu4Dei52uAj3LDDwpmByklYI7p4hI4',
    appId: '1:422724030453:web:e682fe038c75014cde1abc',
    messagingSenderId: '422724030453',
    projectId: 'plantcareplus-b64a2',
    authDomain: 'plantcareplus-b64a2.firebaseapp.com',
    storageBucket: 'plantcareplus-b64a2.firebasestorage.app',
    measurementId: 'G-F9FP0647NR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChBvHiDfwwSutDnotwz6lVkqHTrVl-fe8',
    appId: '1:422724030453:android:108bafc9e87cc7d5de1abc',
    messagingSenderId: '422724030453',
    projectId: 'plantcareplus-b64a2',
    storageBucket: 'plantcareplus-b64a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBM78A5sov_AN0BGM_qgOrq5rm6PNvk1No',
    appId: '1:422724030453:ios:16a869a73c7b6e70de1abc',
    messagingSenderId: '422724030453',
    projectId: 'plantcareplus-b64a2',
    storageBucket: 'plantcareplus-b64a2.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBM78A5sov_AN0BGM_qgOrq5rm6PNvk1No',
    appId: '1:422724030453:ios:16a869a73c7b6e70de1abc',
    messagingSenderId: '422724030453',
    projectId: 'plantcareplus-b64a2',
    storageBucket: 'plantcareplus-b64a2.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZOlu4Dei52uAj3LDDwpmByklYI7p4hI4',
    appId: '1:422724030453:web:214bf72837f8f3d3de1abc',
    messagingSenderId: '422724030453',
    projectId: 'plantcareplus-b64a2',
    authDomain: 'plantcareplus-b64a2.firebaseapp.com',
    storageBucket: 'plantcareplus-b64a2.firebasestorage.app',
    measurementId: 'G-8NM86B3T5R',
  );
}
